### ISSUE TITLE
royalroadl.com changed site format

### ISSUE THREAD

**Issue by synergy1095** [Aivean/royalroad-downloader#2]
royalroadl seems to have entirely changed the site format so the program no longer works

**Comment by xam54321** [comment]
yep, stopped working for me as well :(

Exception in thread "main" java.util.NoSuchElementException
    at java.util.AbstractList$Itr.next(AbstractList.java:350)
    at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
    at scala.collection.IterableLike$class.head(IterableLike.scala:107)
    at scala.collection.AbstractIterable.head(Iterable.scala:54)
    at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$4.apply(HtmlExtractor.scala:89)
    at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$4.apply(HtmlExtractor.scala:89)
    at net.ruippeixotog.scalascraper.scraper.SimpleExtractor.extract(HtmlExtractor.scala:63)
    at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps$$anonfun$extract$1.apply(ScrapingOps.scala:16)
    at scalaz.Monad$$anonfun$map$1$$anonfun$apply$2.apply(Monad.scala:14)
    at scalaz.IdInstances$$anon$1.point(Id.scala:18)
    at scalaz.Monad$$anonfun$map$1.apply(Monad.scala:14)
    at scalaz.IdInstances$$anon$1.bind(Id.scala:20)
    at scalaz.Monad$class.map(Monad.scala:14)
    at scalaz.IdInstances$$anon$1.map(Id.scala:17)
    at scalaz.syntax.FunctorOps.map(FunctorSyntax.scala:9)
    at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.extract(ScrapingOps.scala:16)
    at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$greater$greater(ScrapingOps.scala:20)
    at com.aivean.royalroad.Main$.delayedEndpoint$com$aivean$royalroad$Main$1(Main.scala:19)
    at com.aivean.royalroad.Main$delayedInit$body.apply(Main.scala:8)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.aivean.royalroad.Main$.main(Main.scala:8)
    at com.aivean.royalroad.Main.main(Main.scala)

**Comment by Aivean** [comment]
Thanks for the reports, I'll take a look.
