### ISSUE TITLE
Cannot handle many-chapter stories

### ISSUE THREAD

**Issue by Luingar** [Aivean/royalroad-downloader#4]
encountered with http://royalroadl.com/fiction/4293, which has over 100 chapters.
From what i can tell, the app cannot handle this story because it has so many chapters, the read times out

`Exception in thread "main" java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:516)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
        at net.ruippeixotog.scalascraper.browser.Browser.executeRequest(Browser.scala:42)
        at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$4.apply(Browser.scala:65)
        at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$4.apply(Browser.scala:65)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:20)
        at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:51)
        at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by Aivean** [comment]
Thanks for reporting, I'll take a look.

**Comment by Luingar** [comment]
my hero <3
