### ISSUE TITLE
Error 520 when downloading

### ISSUE THREAD

**Issue by Luingar** [Aivean/royalroad-downloader#9]
Love your tool. New error. :sheep: 

`downloading: http://royalroadl.com/fiction/15935/there-is-no-epic-loot-here-only
-puns/chapter/201782/52-griminology
Exception in thread "main" org.jsoup.HttpStatusException: HTTP error fetching UR
L. Status=520, URL=http://royalroadl.com/fiction/15935/there-is-no-epic-loot-her
e-only-puns/chapter/185868/6-the-capped-limit
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:
679)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:
628)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:260)
        at net.ruippeixotog.scalascraper.browser.JsoupBrowser.executeRequest(Jso
upBrowser.scala:65)
        at net.ruippeixotog.scalascraper.browser.JsoupBrowser$$anonfun$3.apply(J
soupBrowser.scala:76)
        at net.ruippeixotog.scalascraper.browser.JsoupBrowser$$anonfun$3.apply(J
soupBrowser.scala:76)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at net.ruippeixotog.scalascraper.browser.JsoupBrowser.get(JsoupBrowser.s
cala:33)
        at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:62)
        at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:59)
        at scala.collection.parallel.AugmentedIterableIterator$class.map2combine
r(RemainsIterator.scala:115)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2c
ombiner(ParVector.scala:62)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.sc
ala:1054)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.
scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:4
8)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:4
8)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike
.scala:1051)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class
.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTa
sk.internal(Tasks.scala:443)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class
.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTa
sk.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:1
60)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
        at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.
scala:378)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTa
sk.sync(Tasks.scala:443)
        at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Ta
sks.scala:426)
        at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(Ta
skSupport.scala:56)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParItera
bleLike.scala:958)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.
scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:4
8)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:4
8)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIt
erableLike.scala:953)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class
.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTa
sk.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:1
60)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)

C:\Users\User\Downloads>echo "java -jar royalroadl-downloader-assembly-1.2.3.jar
 http://royalroadl.com/fiction/15935" error.txt
"java -jar royalroadl-downloader-assembly-1.2.3.jar http://royalroadl.com/fictio
n/15935" error.txt`

**Comment by Aivean** [comment]
Thanks for the love and error reporting.

This appears to be an error on royalroadl side.  Different runs produce error on different chapters. I'll add retry to chapter downloading. Hopefully it will resolve the issue.

**Comment by Aivean** [comment]
@Luingar, please check the latest release https://github.com/Aivean/royalroadl-downloader/releases/tag/1.2.4
